import fs from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import { spawn } from 'node:child_process'

export type ProjectTemplateId = 'vanilla-ts' | 'react-vite' | 'express-api' | 'python-cli'

export type ProjectTemplate = {
  id: ProjectTemplateId
  label: string
  description: string
  stack: string
  installCommand?: string
  buildCommand?: string
  devCommand?: string
}

export type ProjectBuildRequest = {
  name?: string
  template?: ProjectTemplateId
  basePath?: string
  approved?: boolean
  runInstall?: boolean
  runBuild?: boolean
  openVsCode?: boolean
  openExplorer?: boolean
}

export type ProjectBuildResult = {
  ok: boolean
  projectName: string
  projectPath: string
  template: ProjectTemplate
  filesWritten: string[]
  logs: string[]
  nextCommands: string[]
}

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'vanilla-ts',
    label: 'Zero-dependency TypeScript App',
    description: 'A fast browser app scaffold with TypeScript-style structure and a local validation script. No npm install required.',
    stack: 'HTML + CSS + JavaScript + local validator',
    buildCommand: 'npm run build',
    devCommand: 'npm run dev',
  },
  {
    id: 'react-vite',
    label: 'React + Vite + TypeScript',
    description: 'Modern React starter with Vite scripts, TypeScript config, and a polished app shell.',
    stack: 'React + Vite + TypeScript',
    installCommand: 'npm install',
    buildCommand: 'npm run build',
    devCommand: 'npm run dev',
  },
  {
    id: 'express-api',
    label: 'Express API Service',
    description: 'Node/Express API scaffold with health route, scripts, and TypeScript server entry.',
    stack: 'Node + Express + TypeScript',
    installCommand: 'npm install',
    buildCommand: 'npm run build',
    devCommand: 'npm run dev',
  },
  {
    id: 'python-cli',
    label: 'Python CLI Tool',
    description: 'Python command-line project with package layout, tests folder, and smoke command.',
    stack: 'Python CLI',
    buildCommand: 'python -m py_compile src/main.py',
    devCommand: 'python src/main.py --help',
  },
]

function templateById(id: string | undefined): ProjectTemplate {
  return PROJECT_TEMPLATES.find(template => template.id === id) ?? PROJECT_TEMPLATES[0]
}

function cleanProjectName(value: string | undefined): string {
  const cleaned = (value ?? 'ultron-project').trim().toLowerCase().replace(/[^a-z0-9-_]+/g, '-').replace(/^-+|-+$/g, '')
  return cleaned || 'ultron-project'
}

function resolveBasePath(value: string | undefined): string {
  const fallback = path.join(os.homedir(), 'Ultron Projects')
  if (!value?.trim()) return fallback
  const expanded = value.trim().replace(/^~(?=[/\\]|$)/, os.homedir())
  return path.resolve(expanded)
}

function quotePowerShell(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

async function runCommand(command: string, cwd: string, timeoutSec = 180): Promise<string> {
  return new Promise(resolve => {
    const proc = spawn('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', command], {
      cwd,
      windowsHide: true,
      stdio: 'pipe',
    })
    let stdout = ''
    let stderr = ''
    let settled = false
    const timer = setTimeout(() => {
      settled = true
      proc.kill('SIGTERM')
      resolve(`Error: command timed out after ${timeoutSec}s`)
    }, timeoutSec * 1000)
    proc.stdout.on('data', chunk => { stdout += chunk.toString() })
    proc.stderr.on('data', chunk => { stderr += chunk.toString() })
    proc.on('close', code => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      const output = [stdout.trim(), stderr.trim()].filter(Boolean).join('\n') || '(no output)'
      resolve(code === 0 ? output : `${output}\n[exit code ${code ?? '?'}]`)
    })
    proc.on('error', err => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      resolve(`Error: ${err.message}`)
    })
  })
}

async function writeFiles(root: string, files: Record<string, string>): Promise<string[]> {
  const written: string[] = []
  for (const [relativePath, content] of Object.entries(files)) {
    const fullPath = path.join(root, relativePath)
    await fs.mkdir(path.dirname(fullPath), { recursive: true })
    await fs.writeFile(fullPath, content, 'utf-8')
    written.push(relativePath)
  }
  return written
}

function vanillaFiles(name: string): Record<string, string> {
  return {
    'package.json': JSON.stringify({
      name,
      version: '0.1.0',
      private: true,
      type: 'module',
      scripts: {
        dev: 'node scripts/dev-server.mjs',
        build: 'node scripts/check.mjs',
        check: 'node scripts/check.mjs',
      },
    }, null, 2) + '\n',
    'README.md': `# ${name}\n\nGenerated by Ultron Project Builder.\n\n## Commands\n\n- npm run dev\n- npm run build\n`,
    'index.html': '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>Ultron Project</title>\n    <link rel="stylesheet" href="./src/styles.css" />\n  </head>\n  <body>\n    <main id="app"></main>\n    <script type="module" src="./src/main.js"></script>\n  </body>\n</html>\n',
    'src/main.js': `import { createApp } from './ui.js'\n\ndocument.querySelector('#app').append(createApp())\n`,
    'src/ui.js': `export function createApp() {\n  const root = document.createElement('section')\n  root.className = 'app-shell'\n  root.innerHTML = \`\n    <p class="eyebrow">Generated by Ultron</p>\n    <h1>${name}</h1>\n    <p>Start shaping the product logic, UI states, and workflows here.</p>\n    <div class="actions">\n      <button type="button">Primary action</button>\n      <button type="button" class="secondary">Secondary</button>\n    </div>\n  \`\n  return root\n}\n`,
    'src/styles.css': `:root { color-scheme: light; font-family: Georgia, 'Times New Roman', serif; background: #f5f1e8; color: #1e293b; }\nbody { margin: 0; min-height: 100vh; display: grid; place-items: center; }\n.app-shell { width: min(760px, calc(100vw - 32px)); padding: 48px; border: 1px solid #d4c5aa; background: #fffdf7; box-shadow: 0 20px 60px rgba(30,41,59,.12); }\n.eyebrow { margin: 0 0 12px; text-transform: uppercase; font-size: 12px; letter-spacing: .12em; color: #047857; font-weight: 700; }\nh1 { margin: 0 0 16px; font-size: clamp(40px, 7vw, 82px); line-height: .95; }\np { font-size: 18px; line-height: 1.6; }\n.actions { display: flex; gap: 12px; margin-top: 28px; }\nbutton { border: 1px solid #047857; background: #047857; color: white; padding: 12px 16px; font-weight: 700; cursor: pointer; }\nbutton.secondary { background: transparent; color: #047857; }\n`,
    'scripts/check.mjs': `import fs from 'node:fs'\n\nconst required = ['index.html', 'src/main.js', 'src/ui.js', 'src/styles.css']\nconst missing = required.filter(file => !fs.existsSync(file))\nif (missing.length) {\n  console.error('Missing files:', missing.join(', '))\n  process.exit(1)\n}\nconsole.log('Project structure valid:', required.join(', '))\n`,
    'scripts/dev-server.mjs': `import { createServer } from 'node:http'\nimport { readFile } from 'node:fs/promises'\nimport path from 'node:path'\n\nconst types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' }\nconst server = createServer(async (req, res) => {\n  const urlPath = req.url === '/' ? '/index.html' : req.url ?? '/index.html'\n  const file = path.join(process.cwd(), urlPath.replace(/^\\//, ''))\n  try {\n    const body = await readFile(file)\n    res.writeHead(200, { 'content-type': types[path.extname(file)] ?? 'text/plain' })\n    res.end(body)\n  } catch {\n    res.writeHead(404); res.end('Not found')\n  }\n})\nserver.listen(5174, () => console.log('Dev server: http://localhost:5174'))\n`,
  }
}

function reactFiles(name: string): Record<string, string> {
  return {
    'package.json': JSON.stringify({ name, version: '0.1.0', private: true, type: 'module', scripts: { dev: 'vite', build: 'tsc -b && vite build', preview: 'vite preview' }, dependencies: { '@vitejs/plugin-react': '^6.0.3', vite: '^8.1.1', typescript: '~6.0.2', react: '^19.2.7', 'react-dom': '^19.2.7', 'lucide-react': '^1.22.0' }, devDependencies: { '@types/react': '^19.2.17', '@types/react-dom': '^19.2.3' } }, null, 2) + '\n',
    'index.html': '<div id="root"></div><script type="module" src="/src/main.tsx"></script>\n',
    'tsconfig.json': JSON.stringify({ compilerOptions: { target: 'ES2022', useDefineForClassFields: true, lib: ['ES2022', 'DOM', 'DOM.Iterable'], allowJs: false, skipLibCheck: true, esModuleInterop: true, allowSyntheticDefaultImports: true, strict: true, forceConsistentCasingInFileNames: true, module: 'ESNext', moduleResolution: 'Bundler', resolveJsonModule: true, isolatedModules: true, noEmit: true, jsx: 'react-jsx' }, include: ['src'] }, null, 2) + '\n',
    'src/main.tsx': `import React from 'react'\nimport { createRoot } from 'react-dom/client'\nimport { Sparkles } from 'lucide-react'\nimport './styles.css'\n\nfunction App() {\n  return <main className="shell"><Sparkles /><p>Ultron Project</p><h1>${name}</h1><button>Build the first workflow</button></main>\n}\n\ncreateRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)\n`,
    'src/styles.css': `body { margin: 0; min-height: 100vh; display: grid; place-items: center; background: #e8f3f0; color: #10231f; font-family: Cambria, Georgia, serif; }\n.shell { width: min(720px, calc(100vw - 32px)); padding: 48px; background: white; border: 1px solid #9ab8af; }\nh1 { font-size: 64px; margin: 8px 0 24px; }\nbutton { padding: 12px 16px; border: 0; background: #0f766e; color: white; font-weight: 800; }\n`,
  }
}

function expressFiles(name: string): Record<string, string> {
  return {
    'package.json': JSON.stringify({ name, version: '0.1.0', private: true, type: 'module', scripts: { dev: 'tsx watch src/server.ts', build: 'tsc -p tsconfig.json', start: 'node dist/server.js' }, dependencies: { express: '^5.2.1', cors: '^2.8.6' }, devDependencies: { '@types/express': '^5.0.6', '@types/cors': '^2.8.19', '@types/node': '^24.13.2', tsx: '^4.22.4', typescript: '~6.0.2' } }, null, 2) + '\n',
    'tsconfig.json': JSON.stringify({ compilerOptions: { target: 'ES2022', module: 'NodeNext', moduleResolution: 'NodeNext', strict: true, esModuleInterop: true, outDir: 'dist', rootDir: 'src', skipLibCheck: true }, include: ['src/**/*.ts'] }, null, 2) + '\n',
    'src/server.ts': `import express from 'express'\nimport cors from 'cors'\n\nconst app = express()\napp.use(cors())\napp.use(express.json())\napp.get('/health', (_req, res) => res.json({ ok: true, service: '${name}' }))\napp.listen(3000, () => console.log('${name} listening on http://localhost:3000'))\n`,
    'README.md': `# ${name}\n\nExpress API generated by Ultron Project Builder.\n`,
  }
}

function pythonFiles(name: string): Record<string, string> {
  return {
    'README.md': `# ${name}\n\nPython CLI generated by Ultron Project Builder.\n`,
    'src/main.py': `import argparse\n\ndef main():\n    parser = argparse.ArgumentParser(description='${name} CLI')\n    parser.add_argument('--name', default='Ultron')\n    args = parser.parse_args()\n    print(f'Hello, {args.name}.')\n\nif __name__ == '__main__':\n    main()\n`,
    'tests/.gitkeep': '',
  }
}

function filesForTemplate(template: ProjectTemplate, name: string): Record<string, string> {
  switch (template.id) {
    case 'react-vite': return reactFiles(name)
    case 'express-api': return expressFiles(name)
    case 'python-cli': return pythonFiles(name)
    default: return vanillaFiles(name)
  }
}

export async function buildProject(request: ProjectBuildRequest): Promise<ProjectBuildResult> {
  if (!request.approved) throw new Error('Project Builder requires approval before creating files or opening tools.')
  const template = templateById(request.template)
  const projectName = cleanProjectName(request.name)
  const basePath = resolveBasePath(request.basePath)
  const projectPath = path.join(basePath, projectName)
  const logs: string[] = []
  await fs.mkdir(projectPath, { recursive: true })
  logs.push(`Created project folder: ${projectPath}`)
  const filesWritten = await writeFiles(projectPath, filesForTemplate(template, projectName))
  logs.push(`Wrote ${filesWritten.length} file(s).`)

  if (request.runInstall && template.installCommand) {
    logs.push(`Running: ${template.installCommand}`)
    logs.push(await runCommand(template.installCommand, projectPath, 300))
  } else if (template.installCommand) {
    logs.push(`Skipped install. Run later: ${template.installCommand}`)
  }

  if (request.runBuild && template.buildCommand) {
    if (template.installCommand && !request.runInstall) logs.push(`Skipped build until dependencies are installed: ${template.buildCommand}`)
    else {
      logs.push(`Running: ${template.buildCommand}`)
      logs.push(await runCommand(template.buildCommand, projectPath, 180))
    }
  }

  if (request.openExplorer) {
    logs.push('Opening project folder in File Explorer.')
    logs.push(await runCommand(`Start-Process explorer.exe -ArgumentList ${quotePowerShell(projectPath)}`, projectPath, 20))
  }
  if (request.openVsCode) {
    logs.push('Opening project in VS Code.')
    logs.push(await runCommand(`Start-Process code -ArgumentList ${quotePowerShell(projectPath)}`, projectPath, 20))
  }

  return {
    ok: true,
    projectName,
    projectPath,
    template,
    filesWritten,
    logs,
    nextCommands: [template.installCommand, template.buildCommand, template.devCommand].filter((value): value is string => Boolean(value)),
  }
}